#!/usr/bin/env bash
#Bash script that installs HAProxy & makes configurations

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 5819-webs
    bind *:80
    mode http
    balance roundrobin
    server 6840-web-01 34.227.31.192:80 check
    server 6840-web-02 3.86.232.203:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
